services:
  csv_pdf_mailer:
    build: .
    container_name: csv_pdf_mailer
    ports:
      - "7632:7632"
    volumes:
      - ./logs:/logs
      - ./.secrets:/secrets
    environment:
      - TZ=America/New_York
    restart: unless-stopped
