
[project]
name = "csv-pdf-mailer"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn",
    "loguru",
    "pandas",
    "reportlab",
    "google-api-python-client",
    "google-auth",
    "google-auth-oauthlib"
]
